# Generated by Django 5.2.6 on 2025-09-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescriptions', models.TextField(blank=True, help_text='Medications prescribed')),
                ('lab_results', models.TextField(blank=True, help_text='Any lab findings/results')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional appointment associated with this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.appointment')),
                ('created_by', models.ForeignKey(blank=True, help_text='Doctor or Nurse who authored this record', limit_choices_to={'role__in': ['DOCTOR', 'NURSE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
