# Generated by Django 5.2.6 on 2025-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_assigned_doctor_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes_for_doctor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
