# Generated by Django 5.2.6 on 2025-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Practitioner'), ('pediatrician', 'Pediatrician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('neurosurgeon', 'Neurosurgeon'), ('orthopedic', 'Orthopedic Surgeon'), ('gynecologist', 'Gynecologist'), ('psychiatrist', 'Psychiatrist'), ('radiologist', 'Radiologist'), ('anesthesiologist', 'Anesthesiologist'), ('ent', 'ENT Specialist'), ('ophthalmologist', 'Ophthalmologist'), ('urologist', 'Urologist'), ('other', 'Other')], help_text='Applicable if the user is a Doctor', max_length=50),
        ),
    ]
