# Generated by Django 5.2.6 on 2025-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Beats per minute', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Attended', 'Attended'), ('Discharged', 'Discharged')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
    ]
